namespace: prac-helm

# =====================
# Ingress Configuration
# =====================
ingress:
  enabled: true
  host: localhost   # or your Minikube IP if not using localhost

# =====================
# MySQL Configuration
# =====================
mysql:
  image: mysql:8.0
  rootPassword: root
  database: examdb205
  service:
    port: 3306
    type: ClusterIP

# =====================
# Backend Configuration
# =====================
backend:
  image: jeevani805/helmkillback:latest
  replicas: 2
  port: 2000
  nodePort: 30003
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50

# =====================
# Frontend Configuration
# =====================
frontend:
  image: jeevani805/helmkillfront:latest
  replicas: 2
  port: 80
  nodePort: 30075
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50

  # Point frontend to backend service
  apiUrl: "/api"